import type { Metadata } from "next";
import { inter } from "@/lib/fonts";
import "./globals.css";
import { Footer } from "@/components/footer/footer";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
	title: "Recetas AI",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es">
			<body className={inter.className}>
				{children}
				<Toaster />
				<Footer />
			</body>
		</html>
	);
}
